Project1
TALKER2k/java-course-2023 pull request #4
Opened 2023-10-11 18:52 UTC by TALKER2k

Project1

2023-10-17 20:17 UTC, kkmikhaylova requested changes
Нужно поработать над структурой кода

2023-10-17 20:17 UTC, kkmikhaylova commented on src/main/java/edu/project1/GuessResult.java
> +    public GuessResult(int userAttempts, String resultMessage) {
Какую версию java используешь? С 16 появились records, которые очень упрощают работу с pojo классами, теперь писать полотно из геттеров и сеттеров не нужно) Из альтернатив есть lombok (🤞) и kotlin. Глянь пример в задании, там как раз records использованы

2023-10-17 20:17 UTC, kkmikhaylova commented on src/main/java/edu/project1/ConsoleHangman.java
> +            String resultMessage = "You won! :)";
Строковые константы лучше выносить в static переменные в некоторых случаях. Например, если вынести эту, то в тестах можно будет не дублировать строку `You won! :)`, а подтянуть static переменную

2023-10-20 16:19 UTC, TALKER2k commented on src/main/java/edu/project1/GuessResult.java
> +    public GuessResult(int userAttempts, String resultMessage) {
рекорды я использовал, под методом run они были. И про ломбок тоже знаю, но не знал, можно ли использовать какие-то другие зависимости, кроме тех, что в шаблоне.

2023-10-20 16:22 UTC, TALKER2k commented on src/test/java/edu/project1/Project1Test.java
> +    void runWinnerTest() {
Не совсем понял, что я должен сделать, но я вынес в метод инициализацию session.

2023-10-20 16:25 UTC, TALKER2k commented on src/main/java/edu/project1/ConsoleHangman.java
> +        if (session.getAnswer().length() >= 50 || session.getAnswer().length() == 1) {
В условии: Игра не запускается, если загадываемое слово имеет некорректную длину
И я просто решил сделать, чтобы слова больше 50 символов не пропускались.

2023-10-20 21:47 UTC, kkmikhaylova requested changes

2023-10-20 21:47 UTC, kkmikhaylova commented on src/test/java/edu/hw1/Task5Test.java
> +        int number5 = 9765;
Старайся не пропускать в PR изменения из других задач

2023-10-20 21:47 UTC, kkmikhaylova commented on src/main/java/edu/project1/Session.java
> +    public boolean isActiveSession() {
Название метода не соответствует его логике, число ошибок не имеет отношения к активности сессии

2023-10-20 21:47 UTC, kkmikhaylova commented on src/main/java/edu/project1/HangmanIO.java
> +            if (input.length() == 1 || "quit".equals(input)) {
Лучше при получении `quit` выбрасывать исключение, это позволит возвращать из метода char и избавиться от дополнительных проверок в `ConsoleHangman`

2023-10-20 21:47 UTC, kkmikhaylova commented on src/main/java/edu/project1/ConsoleHangman.java
> +        if (session.getAnswer().length() >= MAX_LENGTH || session.getAnswer().length() == 1) {
Здесь нарушается логика запуска игры
Если у нас уже есть слово в session, что откуда мы его взяли? Игрок запуская игру сам себе загадает слово? Если нет, то и слову здесь взяться неоткуда, стало быть можно эту проверку удалить
Если у нас нет слова в session, то можно эту проверку удалить (а сейчас вообще получим NPE)

Я поняла, зачем ты добавил проверку длины слова, но в кейсе когда мы слово можем получить только от словаря, эта проверка должна располагаться ниже получения слова из словаря

2023-10-20 21:47 UTC, kkmikhaylova commented on src/test/java/edu/project1/Project1Test.java
> +    void runWinnerTest() {
Сейчас все тесты написаны на один метод, который представляет собой всю игру вообще, протестировать корректно кроме этого метода можно разве что `HangmanIO`, но тестов на него нет. Нужно переработать структуру кода, как я писала здесь https://github.com/TALKER2k/java-course-2023/pull/4#discussion_r1362669980 и покрыть тестами все возможные методы

2023-10-21 14:35 UTC, TALKER2k commented
переписал немного. Рекорды оставил в ConsoleHangman файле внизу

2023-10-22 19:28 UTC, kkmikhaylova approved these changes
👍

2023-10-22 19:58 UTC, merged